version: 1.2
workflows:
  - subclass: WDL
    name: FederatedGenotypeImputationPipeline
    primaryDescriptorPath: /federated_imputation_pipeline.wdl
    testParameterFiles:
      - /test_input.json
    authors:
      - name: Mamana Mbiyavanga
        email: mamana.mbiyavanga@uct.ac.za
    topic: Federated genotype imputation pipeline
